name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: hymurcia
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        run: |
          git checkout --orphan output
          git reset --hard
          cp dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update snake animation"
          git push --force origin output
